# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03ed7507968613a64725f61a433189ca44694c9a8d9ca9b3e68cf284b599c22f4f82b5c4775e3a026683d3d033d47db70289062534cfbfdb2ae6cf9c97bdf868

test:
  secret_key_base: 4f01c3484e900712daa1285f6e017aff3588d1bc19af4f3cb448122afa803255b4a3b9c1d642c745f20cc30b78c6aa4f32e619984f27fb4de44bf540d653b864

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
